1. Download voxceleb files from this Drive: https://1drv.ms/u/s!AmYq9m5Um8eJjJwQdIIxEnX4_ELPBA?e=nEcboP 
2. create a function that takes in a wav file and returns a np.array
3. take Sinisa's samples and transform them to array
3. modify the create_databases() function to create dataframes (one df has a speaker_id and mfcc_id), the other has (mfcc_id, mfcc_chanel)

# VoxCeleb Data

In [18]:
import copy

import librosa
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchsummary import summary
from typing import Union
from torch.utils.data import Subset
import time
from tqdm import tqdm
from torchvision import transforms, models
from PIL import Image
from scipy.io.wavfile import read
import wave

from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset

In [3]:
import pickle

with open(r"C:\Users\William Hazen\Documents\UofT\Term 1 (F)\MIE 1517\MIE 1517 Projects\audio-speaker-recognition\voxceleb\mfcc_channel_db_64000_16000_13_voxceleb_4s.pkl", 'rb') as f:
    mfcc_vox_channel = pickle.load(f)
    
with open(r"C:\Users\William Hazen\Documents\UofT\Term 1 (F)\MIE 1517\MIE 1517 Projects\audio-speaker-recognition\voxceleb\speaker_mfcc_db_64000_16000_13_voxceleb_4s.pkl", 'rb') as f:
    speaker_vox_channel = pickle.load(f)


In [4]:
speaker_vox_channel

speaker_id mfcc_id
0              0       0
1              0       1
2              0       2
3              0       3
4              0       4
...          ...     ...
98539       1250   98539
98540       1250   98540
98541       1250   98541
98542       1250   98542
98543       1250   98543

[230309 rows x 2 columns]

In [5]:
speaker_vox_channel.groupby('speaker_id').size().sort_values()

speaker_id
923       33
957       33
683       34
557       36
383       36
        ... 
19       867
934      935
1110     937
95      1230
985     1739
Length: 1251, dtype: int64

In [6]:
np.unique(speaker_vox_channel['speaker_id'])

array([0, 1, 2, ..., 1248, 1249, 1250], dtype=object)

In [7]:
mfcc_vox_channel

channel_0  \
mfcc_id                                                      
0        [-187.24637, -149.53009, -151.10945, -153.8774...   
1        [-198.294, -114.487236, -83.88371, -92.66598, ...   
2        [-90.13957, -83.886154, -103.12938, -108.63772...   
3        [-97.715614, -95.80054, -137.73134, -160.00127...   
4        [-176.24092, -117.82418, -104.70973, -99.88144...   
...                                                    ...   
98539    [-330.80063, -327.78192, -347.83435, -344.1253...   
98540    [-294.61, -273.6533, -275.37488, -297.14517, -...   
98541    [-225.88354, -226.80186, -237.11633, -195.2831...   
98542    [-247.55159, -237.84059, -268.7173, -275.7865,...   
98543    [-287.27335, -297.3479, -290.46216, -286.2022,...   

                                                 channel_1  \
mfcc_id                                                      
0        [68.89113, 63.364716, 70.8166, 80.3503, 80.600...   
1        [42.30703, 28.736141, 37.711243, 75.62166, 92....   
2        [79.63759, 71.0854, 63.44264, 70.60083, 82.133...   
3        [81.36412, 106.41818, 153.7273, 151.40231, 133...   
4        [87.8996, 42.825783, -1.0114547, -15.791763, 2...   
...                                                    ...   
98539    [143.96695, 138.84062, 146.81604, 171.92578, 1...   
98540    [79.51431, 80.28789, 45.84243, 26.307404, 27.7...   
98541    [123.229004, 123.10559, 136.71732, 135.45938, ...   
98542    [83.5443, 77.613045, 80.52568, 86.508156, 88.5...   
98543    [113.15141, 114.29088, 100.45266, 65.310715, 4...   

                                                 channel_2  \
mfcc_id                                                      
0        [9.889414, 2.3946476, 2.5752912, -6.69186, -19...   
1        [-6.576665, -0.8904468, -17.23628, -32.981873,...   
2        [-28.5051, -41.391636, -54.700657, -64.014854,...   
3        [-47.480263, -54.040657, -36.57792, -6.042321,...   
4        [37.66838, 57.93568, 61.87578, 57.950085, 37.3...   
...                                                    ...   
98539    [5.2493825, 6.438201, 7.771367, 11.435141, -3....   
98540    [22.709227, 23.548748, 62.38293, 84.82351, 64....   
98541    [-40.97513, -37.30516, -36.633575, -41.941387,...   
98542    [-13.9129925, -8.832979, -2.9761891, -2.731528...   
98543    [26.996624, 23.570654, 21.505531, 43.496574, 7...   

                                                 channel_3  \
mfcc_id                                                      
0        [17.502277, 12.635658, 17.878536, 28.23352, 31...   
1        [47.598827, 54.884617, 52.340027, 45.405674, 4...   
2        [42.649612, 57.943947, 72.27799, 80.52837, 85....   
3        [3.355823, 7.716856, 15.211743, 16.140945, 13....   
4        [43.399086, 23.913319, 10.752448, 13.6803055, ...   
...                                                    ...   
98539    [-18.89615, -6.2175303, 2.1640232, -6.4587803,...   
98540    [40.115936, 26.891975, 3.000686, 0.76056236, 9...   
98541    [-2.7516446, 2.734407, -1.2908036, -7.076807, ...   
98542    [21.8446, 23.562126, 25.545216, 11.795656, 6.3...   
98543    [27.515507, 26.750843, 11.890797, -9.893206, -...   

                                                 channel_4  \
mfcc_id                                                      
0        [-13.575983, -14.448822, -13.248672, -19.11864...   
1        [-10.850039, -14.415745, -12.853505, -12.63353...   
2        [-34.345848, -40.075825, -46.01481, -46.01294,...   
3        [-34.95617, -44.157013, -54.943058, -38.27945,...   
4        [1.8330331, 11.735545, 6.8757973, -0.73776174,...   
...                                                    ...   
98539    [-39.425392, -31.90382, -26.53632, -30.591902,...   
98540    [-21.335892, -15.086145, 7.1925774, 17.158766,...   
98541    [-8.423008, -8.913733, -8.843574, -7.4721355, ...   
98542    [-17.520346, -17.418522, -18.733154, -11.86516...   
98543    [-5.4117494, 5.0884, 22.891861, 36.592224, 38....   

              

In [8]:
mfcc_vox_channel["channel_0"][0]

mfcc_id
0    [-187.24637, -149.53009, -151.10945, -153.8774...
0    [-329.12683, -312.28018, -347.7598, -380.52814...
Name: channel_0, dtype: object

In [143]:
def play_audio(waveform : torch.Tensor, sample_rate : int) -> None:
    """
    Plays audio given a waveform and sample rate
    
    """
    waveform = waveform.numpy()

    num_channels, num_frames = waveform.shape
    if num_channels == 1:
        display(Audio(waveform[0], rate=sample_rate))
    elif num_channels == 2:
        display(Audio((waveform[0], waveform[1]), rate=sample_rate))
    else:
        raise ValueError("Waveform with more than 2 channels are not supported.")

In [10]:
def create_mfcc_databases(dataset, window_size, sample_rate, speaker_dict, number_spectral_coefficients):
    """
    Creates two databases from an audio dataset e.g. librispeech
    
    Inputs
    -----
    
    base_dataset : 
        A pytorch audio dataset like librispeech
    
    window_size : int
        window size to be used to consistently split waveforms

    sample_rate : int
        sample rate in kHz    
    
    speaker_dict : dict
        dictionary of {'speaker_id':encoded_id} pairs          

    number_spectral_coefficients : int
        number of spectral coefficients to keep for the MFCC calculation
        
    Returns
    -------
    speaker_mfcc_db : pd.DataFrame 
        df with shape (index_id, speaker_id, mfcc_id)
    
    mfcc_channel_db : pd.DataFrame
        df with shape (mfcc_id, channel_id)
    
    """
    try:
        speaker_mfcc_db = pd.read_pickle(f'speaker_mfcc_db_{window_size}_{sample_rate}_{number_spectral_coefficients}.pkl')
        mfcc_channel_db = pd.read_pickle(f'mfcc_channel_db_{window_size}_{sample_rate}_{number_spectral_coefficients}.pkl')
    
    except FileNotFoundError:
        speaker_mfcc_db = pd.DataFrame(columns=["speaker_id", "mfcc_id"])
        mfcc_channel_db = pd.DataFrame(columns=["mfcc_id"]+[f"channel_{i}" for i in range(number_spectral_coefficients)]).set_index('mfcc_id')

        idx = 0

        print('Creating a database. Hold tight...')
        for i in tqdm(range(dataset.__len__())):
            (waveform, sample_rate, transcript, speaker_id, chapter_id, utterance_id) = dataset.__getitem__(i)
            waveform_arr = waveform.numpy().flatten()
            splitted_waveform = split_waveform(waveform_arr, window_size) # split waveforms into consistent chunks

            for chunk in splitted_waveform: # transform waveforms into MFCC spectrograms
                mfccs = librosa.feature.mfcc(y=chunk.flatten(), n_mfcc=13, sr=sample_rate)

                speaker_mfcc_db.loc[idx, "speaker_id"] = speaker_dict[speaker_id]
                speaker_mfcc_db.loc[idx, "mfcc_id"] = idx

                for j in range(number_spectral_coefficients):
                    mfcc_channel_db.loc[idx, f"channel_{j}"] = 1
                    mfcc_channel_db.at[idx, f"channel_{j}"] = mfccs[j, :]
                
                idx += 1

        speaker_mfcc_db.to_pickle(f'speaker_mfcc_db_{window_size}_{sample_rate}_{number_spectral_coefficients}.pkl')
        mfcc_channel_db.to_pickle(f'mfcc_channel_db_{window_size}_{sample_rate}_{number_spectral_coefficients}.pkl')

    return speaker_mfcc_db, mfcc_channel_db

In [11]:
def get_datasets(base_dataset, speaker_dict, window_size, sample_rate , train_pct , 
                 val_pct , test_pct , number_spectral_coefficients , cepstral_normalize , 
                 transform=None):
    """
    Wrapper around other functions to create datasets
    
    Inputs
    -----
    
    base_dataset : 
        A pytorch audio dataset like librispeech
    
    speaker_dict : dict
        dictionary of {'speaker_id':encoded_id} pairs          

    window_size : int
        window size to be used to consistently split waveforms

    sample_rate : int
        sample rate in kHz

    train_pct : float
        train percentage
    
    val_pct : float
        validation percentage

    test_pct : float
        Test percentage

    number_spectral_coefficients : int
        number of spectral coefficients to keep for the MFCC calculation
        
    normalize : bool
        whether to apply cepstral normalization
        
    transform : 
        a custom transformation to apply to the dataset
        
    Returns
    -------
    
    mfcc_dataset_train, mfcc_dataset_val, mfcc_dataset_test
    
    """
    speaker_mfcc_db, mfcc_channel_db = create_mfcc_databases(base_dataset, window_size=window_size, sample_rate=sample_rate, speaker_dict=speaker_dict, number_spectral_coefficients=number_spectral_coefficients)

    train_ids, val_ids, test_ids = split_train_test_val(speaker_mfcc_db, train_pct, val_pct, test_pct)
    
    speaker_mfcc_db_train = speaker_mfcc_db.loc[train_ids]
    speaker_mfcc_db_val = speaker_mfcc_db.loc[val_ids]
    speaker_mfcc_db_test = speaker_mfcc_db.loc[test_ids]
    
    if cepstral_normalize:
        cepstral_normalization = CepstralNormalization(number_spectral_coefficients)
        cepstral_normalization.fit(speaker_mfcc_db_train['mfcc_id'].values, mfcc_channel_db)
        normalized_mfcc_channel_db_train = cepstral_normalization.transform(speaker_mfcc_db_train['mfcc_id'].values, mfcc_channel_db)
        normalized_mfcc_channel_db_val = cepstral_normalization.transform(speaker_mfcc_db_val['mfcc_id'].values, mfcc_channel_db)
        normalized_mfcc_channel_db_test = cepstral_normalization.transform(speaker_mfcc_db_test['mfcc_id'].values, mfcc_channel_db)
        mfcc_channel_db = pd.concat([normalized_mfcc_channel_db_train, normalized_mfcc_channel_db_val, normalized_mfcc_channel_db_test])
        
    mfcc_channel_db_train = mfcc_channel_db.loc[speaker_mfcc_db_train['mfcc_id'].values]
    mfcc_channel_db_val = mfcc_channel_db.loc[speaker_mfcc_db_val['mfcc_id'].values]
    mfcc_channel_db_test = mfcc_channel_db.loc[speaker_mfcc_db_test['mfcc_id'].values]
    
    mfcc_dataset_train = MFCCData(speaker_mfcc_db_train, mfcc_channel_db_train, transform=transform)
    mfcc_dataset_val = MFCCData(speaker_mfcc_db_val, mfcc_channel_db_val, transform=transform)
    mfcc_dataset_test = MFCCData(speaker_mfcc_db_test, mfcc_channel_db_test, transform=transform)

    return mfcc_dataset_train, mfcc_dataset_val, mfcc_dataset_test

# Custom Celeb Data

In [149]:
mypath = r"C:\Users\William Hazen\Documents\UofT\Term 1 (F)\MIE 1517\MIE 1517 Projects\audio-speaker-recognition\Celeb Data"
f = []
for (dirpath, dirnames, filenames) in os.walk(mypath):
    break

In [150]:
print("Folders")
dir_name_list = []
count = 0
for i, dirname in enumerate(dirnames):
    count += 1
    dir_name_list.append(dirname)
    print(i, ' ', dirname)

Folders
0   Alison Pill
1   Amy Poehler
2   Chadwick Boseman
3   Cillian Murphy
4   David Letterman
5   Sinisa


In [151]:

import os

def get_filepaths(directory):
    """
    This function will generate the file names in a directory 
    tree by walking the tree either top-down or bottom-up. For each 
    directory in the tree rooted at directory top (including top itself), 
    it yields a 3-tuple (dirpath, dirnames, filenames).
    """
    file_paths = []  # List which will store all of the full filepaths.

    # Walk the tree.
    for root, directories, files in os.walk(directory):
        for filename in files:
            # Join the two strings in order to form the full filepath.
            filepath = os.path.join(root, filename)
            file_paths.append(filepath)  # Add it to the list.

    return file_paths  # Self-explanatory.

# Run the above function and store its results in a variable.   
full_file_paths = get_filepaths(r"C:\Users\William Hazen\Documents\UofT\Term 1 (F)\MIE 1517\MIE 1517 Projects\audio-speaker-recognition\Celeb Data")

In [152]:
name = full_file_paths[0]
content = name[113:-4]
content.split('\\')[1]

'A_Pill_1'

In [153]:
y_test, sr_test = librosa.load(name)
torch.tensor(y_test)

tensor([ 0.0118,  0.0233,  0.0209,  ..., -0.0082,  0.0060, -0.0233])

In [154]:
ifile = wave.open(name)
samples = ifile.getnframes()
audio = ifile.readframes(samples)
audio_as_np = np.frombuffer(audio, dtype="float32")
audio_as_np

array([ 9.2572618e-38,  2.5862228e-37,  3.8794394e-37, ...,
       -1.5056151e+35,  3.2033930e-37,            nan], dtype=float32)

In [155]:
ifile = wave.open(name)
samples = ifile.getnframes()
audio = ifile.readframes(samples)
audio_as_np = np.frombuffer(audio)
audio_as_np

array([ 9.79160597e-296,  1.56660589e-293,  1.41945291e-294, ...,
        2.81393696e-266, -1.70010689e+279, -5.61764107e+306])

In [156]:
filename = full_file_paths[0]
ifile = wave.open(filename)
samples = ifile.getnframes()
audio = ifile.readframes(samples)
audio_as_np = np.frombuffer(audio, dtype=float)
audio_as_np

array([ 9.79160597e-296,  1.56660589e-293,  1.41945291e-294, ...,
        2.81393696e-266, -1.70010689e+279, -5.61764107e+306])

In [171]:
name_list = []
unique_list = []
speaker_ID_list = []
for filename in full_file_paths:
    content = filename[113:-4]
    split_name = content.split('\\')[1]
    unique_list.append(split_name[0:4])
    name_list.append(split_name)    
    if split_name[0:4] == "A_Pi":
        speaker_ID = 10039
    elif split_name[0:4] == "A_Po":
        speaker_ID = 10046
    elif split_name[0:4] == "C_Bo":
        speaker_ID = 10140
    elif split_name[0:4] == "C_Mu":
        speaker_ID = 10212
    elif split_name[0:4] == "D_Le":
        speaker_ID = 10212
    elif split_name[0:4] == "Sini":
        speaker_ID = 1251
    speaker_ID_list.append(speaker_ID)   
    
    
    

In [172]:
speaker_ID_list

[10039,
 10039,
 10039,
 10039,
 10039,
 10039,
 10039,
 10039,
 10039,
 10039,
 10046,
 10046,
 10046,
 10046,
 10046,
 10046,
 10046,
 10046,
 10046,
 10046,
 10140,
 10140,
 10140,
 10140,
 10140,
 10140,
 10140,
 10140,
 10140,
 10140,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 10212,
 1251,
 1251,
 1251,
 1251,
 1251,
 1251,
 1251,
 1251,
 1251,
 1251]

In [168]:
np.unique(unique_list)

array(['A_Pi', 'A_Po', 'C_Bo', 'C_Mu', 'D_Le', 'Sini'], dtype='<U4')

In [ ]:

# import os

# def get_filepaths(directory):
#     """
#     This function will generate the file names in a directory 
#     tree by walking the tree either top-down or bottom-up. For each 
#     directory in the tree rooted at directory top (including top itself), 
#     it yields a 3-tuple (dirpath, dirnames, filenames).
#     """
#     file_paths = []  # List which will store all of the full filepaths.

#     # Walk the tree.
#     for root, directories, files in os.walk(directory):
#         for filename in files:
#             # Join the two strings in order to form the full filepath.
#             filepath = os.path.join(root, filename)
#             file_paths.append(filepath)  # Add it to the list.

#     return file_paths  # Self-explanatory.

# # Run the above function and store its results in a variable.   
# full_file_paths = get_filepaths(r"C:\Users\William Hazen\Documents\UofT\Term 1 (F)\MIE 1517\MIE 1517 Projects\audio-speaker-recognition\Celeb Data")

In [187]:
audio_as_np_list = []
sample_rate_list = []
name_list = []
mfccs_list = []
unique_list = []
speaker_ID_list = []

for filename in full_file_paths:
    content = filename[113:-4]
    split_name = content.split('\\')[1]
    unique_list.append(split_name[0:4])
    name_list.append(split_name)    
    if split_name[0:4] == "A_Pi":
        speaker_ID = 37
    elif split_name[0:4] == "A_Po":
        speaker_ID = 45 
    elif split_name[0:4] == "C_Bo":
        speaker_ID = 139
    elif split_name[0:4] == "C_Mu":
        speaker_ID = 165
    elif split_name[0:4] == "D_Le":
        speaker_ID = 211
    elif split_name[0:4] == "Sini":
        speaker_ID = 1251
    speaker_ID_list.append(speaker_ID)   
    
    y, sr = librosa.load(filename, sr=1600)
    audio_as_np_list.append(y)
    sample_rate_list.append(sr)
    mfccs = librosa.feature.mfcc(y=y, n_mfcc=13, sr=sr)
    mfccs_list.append(mfccs)

In [175]:
len(audio_as_np_list), len(sample_rate_list), len(name_list), len(speaker_ID_list), len(unique_list)

(60, 60, 60, 60, 60)

In [188]:
celeb_df = pd.DataFrame({
                        "Speaker Name": name_list,
                        "NP Waveforms": audio_as_np_list,
                        "Sample Rate": sample_rate_list,
                        "MFCC's": mfccs_list,
                        "speaker_ID_list": speaker_ID_list,
    
}) 

In [189]:
celeb_df

Speaker Name                                       NP Waveforms  \
0         A_Pill_1  [0.013411364, 0.023571905, 0.012701802, 0.0069...   
1        A_Pill_10  [0.0004919073, 9.4081144e-05, -0.0009698772, 0...   
2         A_Pill_2  [-0.002918021, -0.0074602272, -0.0062654247, -...   
3         A_Pill_3  [2.8710778e-07, -2.439551e-07, -7.316243e-07, ...   
4         A_Pill_4  [0.13179499, 0.004738864, -0.011186932, 0.0098...   
5         A_Pill_5  [1.2973961e-08, 5.1246523e-08, 6.123251e-08, -...   
6         A_Pill_6  [0.024118165, -0.102908246, -0.036374018, -0.0...   
7         A_Pill_7  [-5.2922707e-05, -0.00015098983, -7.670425e-05...   
8         A_Pill_8  [-0.010201823, -0.026411835, -0.015610381, 0.0...   
9         A_Pill_9  [-0.0003504373, 0.0026023318, -0.001371127, -0...   
10     A_Poehler_1  [-0.00036778074, -0.0003072154, 0.0003492348, ...   
11    A_Poehler_10  [-0.0021674123, 3.3609802e-05, 0.010745333, 0....   
12     A_Poehler_2  [-1.0540716e-05, -0.00015843827, -0.0002745018...   
13     A_Poehler_3  [0.05467076, 0.103437185, 0.060123444, 0.00875...   
14     A_Poehler_4  [0.00545, -0.0967063, 0.09152304, 0.019991038,...   
15     A_Poehler_5  [-0.001992366, 0.00019100704, -0.005633074, -0...   
16     A_Poehler_6  [0.0015256106, 0.0024384065, 0.00096783525, -0...   
17     A_Poehler_7  [0.004354395, 0.005041887, -0.00683135, -0.000...   
18     A_Poehler_8  [-0.008935627, -0.019818991, 0.007206751, 0.02...   
19     A_Poehler_9  [0.0014785381, -0.020816274, -0.021687105, 0.0...   
20     C_Boseman_1  [1.1336223e-07, 1.4697059e-07, -6.031292e-08, ...   
21    C_Boseman_10  [-0.0006834476, -0.0015668261, -0.0012302493, ...   
22     C_Boseman_2  [-0.0049235327, -0.010816802, -0.009753041, -0...   
23     C_Boseman_3  [-8.3626815e-05, -0.01793141, -0.0002177798, 0...   
24     C_Boseman_4  [-0.06575639, 0.020596562, 0.010283742, 0.0607...   
25     C_Boseman_5  [0.017146904, -0.037828382, -0.18978351, -0.25...   
26     C_Boseman_6  [2.2133116e-07, -7.835523e-08, 1.14512794e-07,...   
27     C_Boseman_7  [0.0018201905, 0.012450572, 0.0027738444, 0.00...   
28     C_Boseman_8  [-0.0033729177, -0.02025282, -0.041838493, -0....   
29     C_Boseman_9  [0.000573654, 0.0013586654, 0.0013158886, 0.00...   
30      C_Murphy_1  [-7.235607e-08, -1.7086013e-07, -1.5365697e-07...   
31     C_Murphy_10  [-0.0186659, -0.09297616, -0.05554634, -0.0034...   
32      C_Murphy_2  [8.5667814e-08, -4.3171937e-07, 1.6820405e-07,...   
33      C_Murphy_3  [1.7486224e-07, 3.5603097e-07, -2.037522e-07, ...   
34      C_Murphy_4  [0.0013156555, 0.051736467, 0.041310377, -0.02...   
35      C_Murphy_5  [-0.052229106, -0.10126821, -0.07510652, -0.07...   
36      C_Murphy_6  [0.036642395, 0.06721808, 0.010125355, 0.01429...   
37      C_Murphy_7  [-0.028628642, -0.044350006, 0.10014234, 0.112...   
38      C_Murphy_8  [0.0067966557, 0.016589869, 0.012806027, 0.007...   
39      C_Murphy_9  [-3.7513774e-07, -4.042795e-07, -1.6531172e-07...   
40   D_Letterman_1  [2.2773766e-07, 4.617578e-07, 5.1490485e-08, 6...   
41  D_Letterman_10  [-0.0639177, -0.07120752, 0.07576507, 0.056696...   
42   D_Letterman_2  [-0.05890055, -0.0026309935, 0.09854043, 0.052...   
43   D_Letterman_3  [0.05285207, 0.0087472275, -0.12424702, -0.064...   
44   D_Letterman_4  [-0.0038177136, -0.0069926777, 0.0036483933, 0...   
45   D_Letterman_5  [-0.002164728, 0.047578696, 0.047668234, 0.017...   
46   D_Letterman_6  [-0.123827554, 0.24520102, -0.20410381, 0.0665...   
47   D_Letterman_7  [-0.036015145, -0.05111443, 0.07432599, -0.026...   
48   D_Letterman_8  [-0.0512527, 0.054157507, 0.06329315, -0.06227...   
49   D_Letterman_9  [0.0053353487, -0.009616282, -0.005153818, 0.0...   
50        Sinisa_1  [-0.004120336, -0.008646765, 0.007275713, -0.0...   
51       Sinisa_10  [-0.0094351685, -0.02044293, 0.016130852, 0.02...   
52        Sinisa_2  [3.6427136e-07, -2.8145436e-07, -8.506157e-07,...   
53        Sinisa_3  [-0.012707649, -0.00081140915, -0.008727627,

- id10039	Alison_Pill (39) -> (37)
- id10046	Amy_Poehler (47) -> (45)
- id10140	Chadwick_Boseman (141) -> (139)
- id10166	Cillian_Murphy	(167) -> (165)
- id10212	David_Letterman (213) -> (211)

In [200]:
sinisa_df = celeb_df[celeb_df["speaker_ID_list"] == 1251]

In [211]:
e_sinisa_df = sinisa_df.drop(["NP Waveforms", "Speaker Name", "Sample Rate"], axis=1)
e_sinisa_df["speaker_id"] = e_sinisa_df["speaker_ID_list"]
e_sinisa_df["mfcc"] = e_sinisa_df["MFCC's"]

In [212]:
e_sinisa_df

MFCC's  speaker_ID_list  \
50  [[-150.0083, -113.192184, -132.91241, -170.337...             1251   
51  [[-108.51038, -45.922688, -52.379158, -74.0102...             1251   
52  [[-307.35986, -246.52373, -229.26007, -198.597...             1251   
53  [[-213.76352, -208.89221, -179.55733, -143.039...             1251   
54  [[-171.19882, -93.35788, -73.2563, -98.05792, ...             1251   
55  [[-113.7628, -112.40339, -112.1716, -99.9618, ...             1251   
56  [[-102.9827, -115.125015, -194.65633, -184.110...             1251   
57  [[-217.4453, -127.81827, -68.95807, -61.032726...             1251   
58  [[-671.4632, -671.4632, -671.4632, -663.3137, ...             1251   
59  [[-121.2038, -110.952126, -134.01118, -89.1948...             1251   

    speaker_id                                               mfcc  
50        1251  [[-150.0083, -113.192184, -132.91241, -170.337...  
51        1251  [[-108.51038, -45.922688, -52.379158, -74.0102...  
52        1251  [[-307.35986, -246.52373, -229.26007, -198.597...  
53        1251  [[-213.76352, -208.89221, -179.55733, -143.039...  
54        1251  [[-171.19882, -93.35788, -73.2563, -98.05792, ...  
55        1251  [[-113.7628, -112.40339, -112.1716, -99.9618, ...  
56        1251  [[-102.9827, -115.125015, -194.65633, -184.110...  
57        1251  [[-217.4453, -127.81827, -68.95807, -61.032726...  
58        1251  [[-671.4632, -671.4632, -671.4632, -663.3137, ...  
59        1251  [[-121.2038, -110.952126, -134.01118, -89.1948...

In [215]:
e_sinisa_df = e_sinisa_df.drop(["MFCC's", "speaker_ID_list"], axis=1)

In [297]:
sinina_id = e_sinisa_df.drop(["mfcc"], axis=1)[0:7]
ext = [98544, 98545, 98546, 98547, 98548, 98549, 98550]

sinina_id["mfcc_id"] = [98544, 98545, 98546, 98547, 98548, 98549, 98550]
sinina_id = sinina_id.set_index(sinina_id.mfcc_id)

In [183]:

filename =  full_file_paths[0]

y, sr = librosa.load(filename)
mfccs = librosa.feature.mfcc(y=y, n_mfcc=13, sr=sr)
mfccs

array([[-315.24527   , -284.81128   , -283.25525   , ..., -129.46599   ,
        -115.147835  , -141.27301   ],
       [  99.57049   ,   85.89661   ,   76.73218   , ...,   54.32218   ,
          34.608192  ,    0.79439354],
       [   1.4887029 ,   -4.058543  ,  -11.636818  , ...,   -5.4683747 ,
          -3.0015993 ,    1.9328    ],
       ...,
       [  -9.977476  ,  -13.875602  ,  -10.922485  , ...,   -9.942442  ,
          -2.528006  ,    1.667707  ],
       [ -19.87944   ,  -21.716846  ,  -23.202488  , ...,    1.7382696 ,
           2.8970196 ,    8.32127   ],
       [   4.083488  ,   -1.2180246 ,  -10.841471  , ...,   -8.516981  ,
          -7.6570687 ,   -2.346367  ]], dtype=float32)

In [184]:

filename =  full_file_paths[0]

y, sr = librosa.load(filename)
mfccs = librosa.feature.mfcc(y=y, n_mfcc=13, sr=1600)
mfccs

array([[-270.45456  , -231.63275  , -225.08325  , ...,  -54.958595 ,
         -25.858362 ,  -25.359573 ],
       [  95.98001  ,   92.857765 ,   91.12718  , ...,   72.87709  ,
          58.849197 ,   29.573273 ],
       [   7.890584 ,   -1.6044667,   -2.4559772, ...,  -21.388416 ,
         -26.175922 ,  -29.343517 ],
       ...,
       [ -10.070546 ,   -9.74527  ,  -12.941551 , ...,  -17.052967 ,
         -15.707249 ,   -8.096355 ],
       [  13.228867 ,   13.543308 ,   10.469415 , ...,   22.815374 ,
          23.979864 ,   20.711506 ],
       [  11.09654  ,    8.446893 ,    5.0415225, ...,   -2.0751357,
          -4.020825 ,   -1.3664007]], dtype=float32)

In [292]:
temp_speaker_vox_channel = pd.DataFrame(speaker_vox_channel).copy()

In [293]:
temp_mfcc_vox_channel = pd.DataFrame(mfcc_vox_channel).copy()

In [294]:
index_val = temp_speaker_vox_channel.index.values.tolist() +  [98544, 98545, 98546, 98547, 98548, 98549, 98550]

In [300]:
temp_sp_vox_channel = pd.concat([temp_speaker_vox_channel, sinina_id])
temp_sp_vox_channel.set_index(temp_sp_vox_channel.mfcc_id)
temp_sp_vox_channel[-10:]

speaker_id mfcc_id
98541       1250   98541
98542       1250   98542
98543       1250   98543
98544       1251   98544
98545       1251   98545
98546       1251   98546
98547       1251   98547
98548       1251   98548
98549       1251   98549
98550       1251   98550

In [301]:
temp_mfcc_vox_channel

channel_0  \
mfcc_id                                                      
0        [-187.24637, -149.53009, -151.10945, -153.8774...   
1        [-198.294, -114.487236, -83.88371, -92.66598, ...   
2        [-90.13957, -83.886154, -103.12938, -108.63772...   
3        [-97.715614, -95.80054, -137.73134, -160.00127...   
4        [-176.24092, -117.82418, -104.70973, -99.88144...   
...                                                    ...   
98539    [-330.80063, -327.78192, -347.83435, -344.1253...   
98540    [-294.61, -273.6533, -275.37488, -297.14517, -...   
98541    [-225.88354, -226.80186, -237.11633, -195.2831...   
98542    [-247.55159, -237.84059, -268.7173, -275.7865,...   
98543    [-287.27335, -297.3479, -290.46216, -286.2022,...   

                                                 channel_1  \
mfcc_id                                                      
0        [68.89113, 63.364716, 70.8166, 80.3503, 80.600...   
1        [42.30703, 28.736141, 37.711243, 75.62166, 92....   
2        [79.63759, 71.0854, 63.44264, 70.60083, 82.133...   
3        [81.36412, 106.41818, 153.7273, 151.40231, 133...   
4        [87.8996, 42.825783, -1.0114547, -15.791763, 2...   
...                                                    ...   
98539    [143.96695, 138.84062, 146.81604, 171.92578, 1...   
98540    [79.51431, 80.28789, 45.84243, 26.307404, 27.7...   
98541    [123.229004, 123.10559, 136.71732, 135.45938, ...   
98542    [83.5443, 77.613045, 80.52568, 86.508156, 88.5...   
98543    [113.15141, 114.29088, 100.45266, 65.310715, 4...   

                                                 channel_2  \
mfcc_id                                                      
0        [9.889414, 2.3946476, 2.5752912, -6.69186, -19...   
1        [-6.576665, -0.8904468, -17.23628, -32.981873,...   
2        [-28.5051, -41.391636, -54.700657, -64.014854,...   
3        [-47.480263, -54.040657, -36.57792, -6.042321,...   
4        [37.66838, 57.93568, 61.87578, 57.950085, 37.3...   
...                                                    ...   
98539    [5.2493825, 6.438201, 7.771367, 11.435141, -3....   
98540    [22.709227, 23.548748, 62.38293, 84.82351, 64....   
98541    [-40.97513, -37.30516, -36.633575, -41.941387,...   
98542    [-13.9129925, -8.832979, -2.9761891, -2.731528...   
98543    [26.996624, 23.570654, 21.505531, 43.496574, 7...   

                                                 channel_3  \
mfcc_id                                                      
0        [17.502277, 12.635658, 17.878536, 28.23352, 31...   
1        [47.598827, 54.884617, 52.340027, 45.405674, 4...   
2        [42.649612, 57.943947, 72.27799, 80.52837, 85....   
3        [3.355823, 7.716856, 15.211743, 16.140945, 13....   
4        [43.399086, 23.913319, 10.752448, 13.6803055, ...   
...                                                    ...   
98539    [-18.89615, -6.2175303, 2.1640232, -6.4587803,...   
98540    [40.115936, 26.891975, 3.000686, 0.76056236, 9...   
98541    [-2.7516446, 2.734407, -1.2908036, -7.076807, ...   
98542    [21.8446, 23.562126, 25.545216, 11.795656, 6.3...   
98543    [27.515507, 26.750843, 11.890797, -9.893206, -...   

                                                 channel_4  \
mfcc_id                                                      
0        [-13.575983, -14.448822, -13.248672, -19.11864...   
1        [-10.850039, -14.415745, -12.853505, -12.63353...   
2        [-34.345848, -40.075825, -46.01481, -46.01294,...   
3        [-34.95617, -44.157013, -54.943058, -38.27945,...   
4        [1.8330331, 11.735545, 6.8757973, -0.73776174,...   
...                                                    ...   
98539    [-39.425392, -31.90382, -26.53632, -30.591902,...   
98540    [-21.335892, -15.086145, 7.1925774, 17.158766,...   
98541    [-8.423008, -8.913733, -8.843574, -7.4721355, ...   
98542    [-17.520346, -17.418522, -18.733154, -11.86516...   
98543    [-5.4117494, 5.0884, 22.891861, 36.592224, 38....   

              

In [311]:
sin_mfcc_sp = e_sinisa_df.drop(["speaker_id"], axis=1)[0:7]


In [340]:
mf_list = sin_mfcc_sp["mfcc"].values
mf_list[0]

array([[-150.0083   , -113.192184 , -132.91241  , ..., -134.08347  ,
        -150.87366  , -200.21469  ],
       [  67.69481  ,   84.73309  ,  108.44603  , ...,   33.751568 ,
          58.52484  ,   91.18417  ],
       [ -38.24385  ,  -62.83754  ,  -81.26061  , ...,  -18.03008  ,
         -24.90793  ,  -31.537476 ],
       ...,
       [ -40.176918 ,  -46.965096 ,  -43.845337 , ...,  -29.000505 ,
         -22.192303 ,  -12.79657  ],
       [ -14.679676 ,  -18.292782 ,  -13.766966 , ...,   -1.0931615,
          -9.689476 ,  -13.624191 ],
       [  12.093235 ,   23.24943  ,    6.091381 , ...,  -20.705822 ,
         -11.486926 ,   -8.620178 ]], dtype=float32)

In [341]:
mf_list = sin_mfcc_sp["mfcc"].values

c=0
c1 = 0
channel_list = []
c_list = []
for count in mf_list:
    c_list.append(count)
    for channel in count:
       channel_list.append(channel)
        

In [345]:
len(c_list)

7

In [346]:
len(channel_list)

91

In [347]:
sin_mfcc_sp["mfcc_id"] = [98544, 98545, 98546, 98547, 98548, 98549, 98550]
sin_mfcc_sp = sin_mfcc_sp.set_index(sin_mfcc_sp.mfcc_id)
sin_mfcc_sp.drop(["mfcc_id", "mfcc"],axis=1)
sin_mfcc_sp["channel_0"] = channel_list


Empty DataFrame
Columns: []
Index: [98544, 98545, 98546, 98547, 98548, 98549, 98550]

In [ ]:
sin_mfcc_sp.pivot_table()

In [ ]:
new_table = [["Row", "Column", "Data"]]
for line in table[1:]:
    for name, cell in zip(table[0], line)[1:]:
        new_line = [line[0], name, cell]
        new_table.append(new_line)

In [313]:
temp_mfcc_vox_channel = pd.concat([temp_mfcc_vox_channel, sin_mfcc_sp])

In [329]:
(temp_mfcc_vox_channel["channel_0"]).values

array([array([-187.24637 , -149.53009 , -151.10945 , -153.87744 , -157.39336 ,
              -167.64201 , -133.19125 , -110.70457 , -126.12043 , -128.65704 ,
              -101.416985,  -91.07796 , -108.27437 , -130.8411  , -116.01906 ,
               -94.87619 , -109.688965, -140.54437 , -157.03706 , -161.57188 ,
              -116.26887 ,  -68.43871 ,  -56.19124 ,  -77.701645,  -90.193   ,
               -99.70789 ,  -91.44558 ,  -91.830605, -116.76227 ,  -82.021774,
               -55.151524,  -67.72641 ,  -89.988785, -124.37212 , -179.39665 ,
              -200.58533 , -205.458   , -178.25829 , -119.096436,  -99.83642 ,
              -107.9164  , -117.80507 , -148.67375 , -171.24449 , -163.25299 ,
              -139.65823 , -103.064255,  -98.835884, -127.48778 , -163.86482 ,
              -138.19537 ,  -95.12578 , -100.05756 , -128.8513  , -123.48403 ,
              -115.790306, -120.04804 , -106.75805 ,  -98.03968 , -104.1702  ,
              -126.53275 , -165.43683 , -146.72174 ,

In [ ]:
# with open('E_Pickle.pkl', 'wb') as f:
#     pickle.dump(temp_sp_vox_channel, f)

# with open('S_Pickle.pkl', 'wb') as f:
#     pickle.dump(S, f)